[package]
name = "phygital"
version = "1.0.0"
authors = []

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-framework'

[dependencies.AptosTokenObjects]
git = 'https://github.com/aptos-labs/aptos-core.git' 
rev = 'main'
subdir = 'aptos-move/framework/aptos-token-objects'

[addresses]
addrx = "0x752d1c37fe7060e599af08f584b6ba0aa989ac163f83424622592f714a8df2e7"
